language: php

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpstan analyse src --level 7
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
