language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install

script:
  - composer test

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover /tmp/coverage.xml